var PASSWORD_RESET_MINUTES_ = 15;
function validEmail_(email){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(email||''));}
function publicAdmin_(a){return {id:a.admin_id,name:a.admin_name||a.email,email:a.email,role:a.role||'user'};}
function register_(input){
  var email=safeText_(input.email,320).toLowerCase(),password=String(input.password===undefined?'':input.password),confirm=String(input.confirmPassword===undefined?'':input.confirmPassword);
  if(!validEmail_(email))throw apiError_('VALIDATION','Email 格式錯誤。');
  if(!password)throw apiError_('VALIDATION','密碼不可空白。');
  if(password!==confirm)throw apiError_('VALIDATION','兩次輸入的密碼不一致。');
  if(password.length>5000)throw apiError_('VALIDATION','密碼內容過長。');
  return withLock_(function(){var ss=master_(),sheet=ss.getSheetByName('管理員設定'),all=rows_(sheet);if(all.some(function(a){return String(a.email).toLowerCase()===email;}))throw apiError_('DUPLICATE','此 Email 已註冊。');var root=DriveApp.getFolderById(PropertiesService.getScriptProperties().getProperty('ROOT_FOLDER_ID')),id=Utilities.getUuid(),folder=root.createFolder('使用者_'+id.slice(0,8)),a={admin_id:id,admin_name:email.split('@')[0],admin_folder_id:folder.getId(),status:'active',created_at:now_(),last_login_at:now_(),email:email,password:password,role:'user',email_verified:true,updated_at:now_()};append_(sheet,a);return {ok:true,data:{token:createSession_('admin',{admin_id:id,admin_name:a.admin_name,email:email,role:'user'}),admin:publicAdmin_(a)}};});
}
function forgotPassword_(input){
  var email=safeText_(input.email,320).toLowerCase();if(!validEmail_(email))throw apiError_('VALIDATION','Email 格式錯誤。');assertLoginRate_('reset',email);failLogin_('reset',email);var ss=master_(),a=rows_(ss.getSheetByName('管理員設定')).find(function(x){return String(x.email).toLowerCase()===email&&x.status==='active';});
  if(a){var token=randomToken_(),resetSheet=ss.getSheetByName('密碼重設紀錄'),front=PropertiesService.getScriptProperties().getProperty('FRONTEND_URL')||'';if(!/^https:\/\//.test(front))throw apiError_('CONFIG','系統尚未設定前端 HTTPS 網址，暫時無法寄送重設信。');append_(resetSheet,{reset_id:Utilities.getUuid(),admin_id:a.admin_id,token_hash:sha256_(token),expires_at:new Date(Date.now()+PASSWORD_RESET_MINUTES_*60000).toISOString(),used_at:'',requested_at:now_()});var url=front.replace(/\/$/,'')+'/#/reset-password?token='+encodeURIComponent(token);MailApp.sendEmail({to:email,subject:'問卷管理系統－重設密碼',name:'問卷管理系統',body:'請在 '+PASSWORD_RESET_MINUTES_+' 分鐘內開啟下列連結重設密碼：\n'+url+'\n若非您本人申請，請忽略此信。',htmlBody:'<p>請在 '+PASSWORD_RESET_MINUTES_+' 分鐘內點擊下方連結重設密碼：</p><p><a href="'+url+'">重設密碼</a></p><p>若非您本人申請，請忽略此信。</p>'});}return {ok:true,message:'若此 Email 已註冊，系統將寄出密碼重設信。'};
}
function resetPassword_(input){var token=safeText_(input.token,500),password=String(input.password===undefined?'':input.password),confirm=String(input.confirmPassword===undefined?'':input.confirmPassword);if(!password)throw apiError_('VALIDATION','密碼不可空白。');if(password!==confirm)throw apiError_('VALIDATION','兩次輸入的密碼不一致。');return withLock_(function(){var ss=master_(),sheet=ss.getSheetByName('密碼重設紀錄'),r=rows_(sheet).find(function(x){return x.token_hash===sha256_(token)&&!x.used_at&&new Date(x.expires_at).getTime()>Date.now();});if(!r)throw apiError_('INVALID_TOKEN','重設連結無效或已逾期。');updateWhere_(ss.getSheetByName('管理員設定'),function(a){return a.admin_id===r.admin_id;},{password:password,updated_at:now_()});updateWhere_(sheet,function(x){return x.reset_id===r.reset_id;},{used_at:now_()});return {ok:true,message:'密碼已更新，請重新登入。'};});}
function adminProfile_(input){var s=session_(input.token,'admin'),a=rows_(master_().getSheetByName('管理員設定')).find(function(x){return x.admin_id===s.admin_id;});if(!a)throw apiError_('NOT_FOUND','找不到帳號。');return {ok:true,data:publicAdmin_(a)};}
function adminUpdateProfile_(input){var s=session_(input.token,'admin'),sheet=master_().getSheetByName('管理員設定'),a=rows_(sheet).find(function(x){return x.admin_id===s.admin_id;}),email=safeText_(input.email||a.email,320).toLowerCase(),password=input.password===undefined?'':String(input.password);if(a.email==='kgi'&&email!=='kgi')throw apiError_('VALIDATION','系統管理者登入名稱不可修改。');if(email!=='kgi'&&!validEmail_(email))throw apiError_('VALIDATION','Email 格式錯誤。');if(rows_(sheet).some(function(x){return x.admin_id!==a.admin_id&&String(x.email).toLowerCase()===email;}))throw apiError_('DUPLICATE','此 Email 已被使用。');var changes={email:email,admin_name:safeText_(input.name||a.admin_name,100),updated_at:now_()};if(password){if(password!==String(input.confirmPassword||''))throw apiError_('VALIDATION','兩次輸入的密碼不一致。');changes.password=password;}updateWhere_(sheet,function(x){return x.admin_id===a.admin_id;},changes);return {ok:true,data:publicAdmin_(Object.assign({},a,changes))};}
