function adminLogin_(input) {
  var email=safeText_(input.email,320).toLowerCase(),password=String(input.password===undefined?'':input.password),rate=email;assertLoginRate_('admin',rate);
  var master=master_(),adminSheet=master.getSheetByName('管理員設定'),admin=rows_(adminSheet).find(function(a){return String(a.email).toLowerCase()===email&&adminPasswordMatches_(a,password)&&a.status==='active';});
  if(!admin){failLogin_('admin',rate); throw apiError_('INVALID_LOGIN','Email 或密碼錯誤。');}
  clearLoginRate_('admin',rate); updateWhere_(adminSheet,function(a){return a.admin_id===admin.admin_id;},{last_login_at:now_()});
  logMaster_(admin.admin_id,'','管理員',admin.admin_id,'登入','系統','','管理員登入成功',master);
  return {ok:true,data:{token:createSession_('admin',{admin_id:admin.admin_id,admin_name:admin.admin_name,email:admin.email,role:admin.role||'user'}),admin:publicAdmin_(admin)}};
}
function adminPasswordMatches_(admin,password){
  var stored=String(admin.password===undefined?'':admin.password);
  if(stored===password)return true;
  // Older sheets converted the fixed numeric password to a number and dropped its leading zero.
  return String(admin.email).toLowerCase()==='kgi'&&password==='03434016'&&stored==='3434016';
}
function adminLogout_(input){session_(input.token,'admin');destroySession_(input.token);return {ok:true};}
function adminSetFrontendUrl_(input){var admin=session_(input.token,'admin'),url=safeText_(input.url,500).replace(/\/$/,'');if(!/^https:\/\//.test(url))throw apiError_('VALIDATION','前端網址必須使用 HTTPS。');PropertiesService.getScriptProperties().setProperty('FRONTEND_URL',url);updateWhere_(master_().getSheetByName('專案索引'),function(p){return p.admin_id===admin.admin_id;},{updated_at:now_()});var sheet=master_().getSheetByName('專案索引'),projects=rows_(sheet);projects.filter(function(p){return p.admin_id===admin.admin_id;}).forEach(function(p){updateWhere_(sheet,function(x){return x.project_id===p.project_id&&x.admin_id===admin.admin_id;},{login_url:url+'/#/survey/'+p.project_id+'/login'});});return {ok:true,data:{url:url}};}

function adminProjects_(input){var a=session_(input.token,'admin');var list=rows_(master_().getSheetByName('專案索引')).filter(function(p){return p.admin_id===a.admin_id;}).map(function(p){return projectSummary_(p);});return {ok:true,data:list};}
function projectSummary_(p,ss){var stats={total:0,loggedIn:0,draft:0,submitted:0,rate:0};try{var validSs=(ss&&typeof ss.getSheetByName==='function')?ss:projectDb_(p);stats=statsFor_(validSs);}catch(_){} return Object.assign({},p,{stats:stats});}

function adminCreateProject_(input){var a=session_(input.token,'admin'),name=safeText_(input.project&&input.project.name,120);if(!name)throw apiError_('VALIDATION','請輸入問卷名稱。');
  return withLock_(function(){var owner=rows_(master_().getSheetByName('管理員設定')).find(function(x){return x.admin_id===a.admin_id&&x.status==='active';});if(!owner)throw apiError_('FORBIDDEN','管理員已停用。');var s=createProjectStorage_(owner,name),now=now_(),payload=input.project||{};
    putSettings_(s.spreadsheet.getSheetByName('專案設定'),{description:safeText_(payload.description,10000),completion_message:safeText_(payload.completionMessage||'您的問卷已成功送出。',1000),show_progress:payload.showProgress!==false,access_mode:'specified',sections:[{id:'S1',title:'問卷內容',description:'',order:1}]});
    var front=PropertiesService.getScriptProperties().getProperty('FRONTEND_URL')||'';var p={project_id:s.projectId,admin_id:a.admin_id,project_name:name,project_status:payload.status||'草稿',folder_id:s.folderId,spreadsheet_id:s.spreadsheetId,login_url:front?front.replace(/\/$/,'')+'/#/survey/'+s.projectId+'/login':'',start_date:payload.startDate||'',end_date:payload.endDate||'',created_at:now,updated_at:now};append_(master_().getSheetByName('專案索引'),p);logMaster_(a.admin_id,p.project_id,'管理員',a.admin_id,'建立專案','專案',p.project_id,'建立 '+name);return {ok:true,data:projectSummary_(p)};});}

function adminProject_(input){var auth=requireAdminProject_(input),ss=projectDb_(auth.project);return {ok:true,data:{project:projectSummary_(auth.project,ss),settings:settingMap_(ss.getSheetByName('專案設定')),fields:rows_(ss.getSheetByName('使用者欄位設定')),schema:attachInventory_(ss,readSchema_(ss)),users:safeUsers_(ss),linkedOptions:rows_(ss.getSheetByName('連結型選項設定'))}};}

function adminUpdateProject_(input){var auth=requireAdminProject_(input),p=input.project||{},allowed=['草稿','開放填寫','停止填寫','已截止','已封存'];if(p.status&&allowed.indexOf(p.status)<0)throw apiError_('VALIDATION','無效的專案狀態。');var changes={updated_at:now_()};if(p.name!==undefined){changes.project_name=safeText_(p.name,120);if(!changes.project_name)throw apiError_('VALIDATION','問卷名稱不可空白。');}if(p.status)changes.project_status=p.status;if(p.startDate!==undefined)changes.start_date=p.startDate;if(p.endDate!==undefined)changes.end_date=p.endDate;if(changes.start_date&&changes.end_date&&new Date(changes.start_date)>new Date(changes.end_date))throw apiError_('VALIDATION','截止日期不可早於開放日期。');
  updateWhere_(master_().getSheetByName('專案索引'),function(x){return x.project_id===auth.project.project_id&&x.admin_id===auth.admin.admin_id;},changes);var settingsChanges={};if(p.description!==undefined)settingsChanges.description=safeText_(p.description,10000);if(p.completionMessage!==undefined)settingsChanges.completion_message=safeText_(p.completionMessage,1000);if(p.showProgress!==undefined)settingsChanges.show_progress=p.showProgress!==false;if(p.accessMode!==undefined)settingsChanges.access_mode=p.accessMode;if(Object.keys(settingsChanges).length>0){putSettings_(projectDb_(auth.project).getSheetByName('專案設定'),settingsChanges);}logProject_(auth.project,'管理員',auth.admin.admin_id,'修改專案','專案',auth.project.project_id,'更新專案設定');return {ok:true};}
function adminArchiveProject_(input){input.project={status:'已封存'};return adminUpdateProject_(input);}
function adminDeleteProject_(input){var auth=requireAdminProject_(input);if(input.confirmText!==auth.project.project_name)throw apiError_('CONFIRM_REQUIRED','請輸入完整問卷名稱確認刪除。');DriveApp.getFolderById(auth.project.folder_id).setTrashed(true);deleteWhere_(master_().getSheetByName('專案索引'),function(x){return x.project_id===auth.project.project_id&&x.admin_id===auth.admin.admin_id;});logMaster_(auth.admin.admin_id,auth.project.project_id,'管理員',auth.admin.admin_id,'刪除專案','專案',auth.project.project_id,'移至垃圾桶');return {ok:true};}

function adminCloneProject_(input){var auth=requireAdminProject_(input),source=projectDb_(auth.project),result=adminCreateProject_({token:input.token,project:{name:safeText_(input.name||auth.project.project_name+'（複製）',120),description:settingMap_(source.getSheetByName('專案設定')).description}}),target=projectDb_(result.data.spreadsheet_id);writeSchema_(target,readSchema_(source));replaceAll_(target.getSheetByName('使用者欄位設定'),rows_(source.getSheetByName('使用者欄位設定')));replaceAll_(target.getSheetByName('一般選項設定'),rows_(source.getSheetByName('一般選項設定')));return result;}

function adminSaveSchema_(input){var auth=requireAdminProject_(input),schema=validateSchema_(input.schema||{}),ss=projectDb_(auth.project);writeSchema_(ss,schema);logProject_(auth.project,'管理員',auth.admin.admin_id,'修改問卷','問卷',auth.project.project_id,'儲存 '+schema.questions.length+' 題',ss);return {ok:true,data:schema};}
function validateSchema_(schema){var types=['short','paragraph','single','checkbox','dropdown','scale','radio_grid','checkbox_grid','date','time','number','email','phone','heading','image_note','section','signature','multi_image','linked_multi','linked_short','linked_matrix','image_choice','star_rating','cascading','ranking','allocation','inventory','heatmap','text_highlight','maxdiff','location','terms'];var ids={},sections=(schema.sections||[]).map(function(s,i){return {id:s.id||('S'+(i+1)),title:safeText_(s.title,200),description:safeText_(s.description,2000),order:i+1};});if(!sections.length)sections=[{id:'S1',title:'問卷內容',description:'',order:1}];var sectionIds={},sectionCounts={};sections.forEach(function(s){if(sectionIds[s.id])throw apiError_('VALIDATION','區段 ID 重複。');sectionIds[s.id]=true;sectionCounts[s.id]=0;});
  var questions=(schema.questions||[]).map(function(q){var id=q.id||('Q'+Utilities.getUuid().replace(/-/g,'').slice(0,10)),sectionId=sectionIds[q.sectionId]?q.sectionId:sections[0].id;if(ids[id])throw apiError_('VALIDATION','題目 ID 重複。');ids[id]=true;if(types.indexOf(q.type)<0)throw apiError_('VALIDATION','不支援的題型：'+q.type);return {id:id,sectionId:sectionId,order:++sectionCounts[sectionId],type:q.type,title:safeText_(q.title,500),description:safeText_(q.description,2000),required:Boolean(q.required),options:(q.options||[]).map(function(o){return typeof o==='string'?{value:o,label:o}:o;}),validation:q.validation||{},config:q.config||{}};});
  questions.forEach(function(q){if(q.type!=='linked_matrix')return;var promptIds={};q.config.prompts=(q.config.prompts||[]).map(function(p,i){var id=safeText_(p.id||('P'+Utilities.getUuid().replace(/-/g,'').slice(0,10)),100),label=safeText_(p.label,500),type=['short','single','checkbox'].indexOf(p.type)>=0?p.type:'short',optionIds={};if(!label)throw apiError_('VALIDATION','連結型矩陣第 '+(i+1)+' 個問項不可空白。');if(promptIds[id])throw apiError_('VALIDATION','連結型矩陣問項 ID 重複。');promptIds[id]=true;var options=type==='short'?[]:(p.options||[]).map(function(o,j){var value=safeText_(o.value||('PO'+Utilities.getUuid().replace(/-/g,'').slice(0,10)),100),optionLabel=safeText_(o.label,300);if(!optionLabel)throw apiError_('VALIDATION',label+'的第 '+(j+1)+' 個選項不可空白。');if(optionIds[value])throw apiError_('VALIDATION',label+'的選項 ID 重複。');optionIds[value]=true;return {value:value,label:optionLabel};});if(type!=='short'&&options.length<1)throw apiError_('VALIDATION',label+'至少需要 1 個選項。');return {id:id,label:label,type:type,required:p.required!==false,options:options,config:p.config||{}};});});assertNoJumpCycle_(sections,questions);return {sections:sections,questions:questions};}
function assertNoJumpCycle_(sections,questions){var order={};sections.forEach(function(s,i){order[s.id]=i;});questions.forEach(function(q){(q.options||[]).forEach(function(o){if(o.nextSectionId&&o.nextSectionId!=='SUBMIT'&&order[o.nextSectionId]===undefined)throw apiError_('VALIDATION','跳題目標區段不存在。');if(o.nextSectionId&&o.nextSectionId!=='SUBMIT'&&order[o.nextSectionId]<=order[q.sectionId])throw apiError_('VALIDATION','條件跳題不可跳回目前或之前的區段。');});});}
function writeSchema_(ss,schema){var q=ss.getSheetByName('問項設計'),o=ss.getSheetByName('一般選項設定'),matrixSheet=ss.getSheetByName('連結型矩陣問項設定'),now=now_();replaceAll_(q,schema.questions.map(function(x){var config=Object.assign({},x.config||{});if(matrixSheet)delete config.prompts;return {question_id:x.id,section_id:x.sectionId,question_order:x.order,type:x.type,title:x.title,description:x.description,required:x.required,config_json:JSON.stringify(config),validation_json:JSON.stringify(x.validation||{}),active:true,updated_at:now};}));var opts=[],matrixPrompts=[];schema.questions.forEach(function(x){(x.options||[]).forEach(function(v,i){var extra=Object.assign({},v);delete extra.value;delete extra.label;delete extra.nextSectionId;opts.push({question_id:x.id,option_value:v.value,option_label:v.label,option_order:i+1,next_section_id:v.nextSectionId||'',active:true,option_config_json:JSON.stringify(extra)});});if(x.type==='linked_matrix')(x.config&&x.config.prompts||[]).forEach(function(p,i){matrixPrompts.push({question_id:x.id,prompt_id:p.id,prompt_label:p.label,prompt_order:i+1,active:true,prompt_type:p.type||'short',prompt_options_json:JSON.stringify(p.options||[]),prompt_required:p.required!==false,prompt_config_json:JSON.stringify(p.config||{})});});});replaceAll_(o,opts);if(matrixSheet)replaceAll_(matrixSheet,matrixPrompts);syncInventoryFromSchema_(ss,schema);putSettings_(ss.getSheetByName('專案設定'),{sections:schema.sections});}
function readSchema_(ss){var settings=settingMap_(ss.getSheetByName('專案設定')),opts=rows_(ss.getSheetByName('一般選項設定')),matrixPrompts=rows_(ss.getSheetByName('連結型矩陣問項設定')),sections=settings.sections||[{id:'S1',title:'問卷內容',description:'',order:1}],sectionOrder={};sections.forEach(function(s,i){sectionOrder[s.id]=Number(s.order)||i+1;});var questions=rows_(ss.getSheetByName('問項設計')).filter(function(q){return String(q.active)!=='false';}).map(function(q){var config=parseJson_(q.config_json,{});if(q.type==='linked_matrix')config.prompts=matrixPrompts.filter(function(p){return p.question_id===q.question_id&&String(p.active)!=='false';}).sort(function(a,b){return a.prompt_order-b.prompt_order;}).map(function(p){return {id:p.prompt_id,label:p.prompt_label,type:p.prompt_type||'short',required:p.prompt_required===''||p.prompt_required===undefined?true:String(p.prompt_required)!=='false',options:parseJson_(p.prompt_options_json,[])||[],config:parseJson_(p.prompt_config_json,{})||{}};});return {id:q.question_id,sectionId:q.section_id,order:Number(q.question_order),type:q.type,title:q.title,description:q.description,required:String(q.required)==='true',config:config,validation:parseJson_(q.validation_json,{}),options:opts.filter(function(o){return o.question_id===q.question_id&&String(o.active)!=='false';}).sort(function(a,b){return a.option_order-b.option_order;}).map(function(o){return Object.assign({value:o.option_value,label:o.option_label,nextSectionId:o.next_section_id||''},parseJson_(o.option_config_json,{}));})};});return {sections:sections,questions:questions.sort(function(a,b){return (sectionOrder[a.sectionId]||999)-(sectionOrder[b.sectionId]||999)||a.order-b.order;})};}

function adminSaveUserFields_(input){var auth=requireAdminProject_(input),fields=input.fields||[],keys={account:true,password:true},normalized=[{field_id:'SYSTEM_ACCOUNT',field_key:'account',field_label:safeText_(input.accountLabel||'業務員代碼',100),field_order:1,field_type:'text',statistical_dimension:true,active:true},{field_id:'SYSTEM_PASSWORD',field_key:'password',field_label:safeText_(input.passwordLabel||'生日後四碼',100),field_order:2,field_type:'password',statistical_dimension:false,active:true}];fields.forEach(function(f,i){var key=safeText_(f.field_key||f.key,60).replace(/[^A-Za-z0-9_]/g,'_');if(!key||keys[key])throw apiError_('VALIDATION','欄位名稱重複或為保留名稱。');keys[key]=true;normalized.push({field_id:f.field_id||Utilities.getUuid(),field_key:key,field_label:safeText_(f.field_label||f.label,100),field_order:i+3,field_type:f.field_type||'text',statistical_dimension:f.statistical_dimension!==false,active:f.active!==false});});replaceAll_(projectDb_(auth.project).getSheetByName('使用者欄位設定'),normalized);return {ok:true,data:normalized};}

function adminImportUsers_(input){var auth=requireAdminProject_(input),ss=projectDb_(auth.project),sheet=ss.getSheetByName('問卷使用者設定'),fieldSheet=ss.getSheetByName('使用者欄位設定'),existingFields=fieldSheet?rows_(fieldSheet):[],existing=rows_(sheet),map={};existing.forEach(function(u){map[u.account]=u;});var seen={},errors=[],mode=input.duplicateMode||'skip';(input.users||[]).forEach(function(raw,index){var account=safeText_(raw.account,100),password=safeText_(raw.password,200);if(!account)errors.push({row:index+1,message:'帳號不可空白'});if(seen[account])errors.push({row:index+1,message:'匯入資料內帳號重複'});seen[account]=true;if(!map[account]&&!password)errors.push({row:index+1,message:'新帳號密碼不可空白'});});if(errors.length)throw apiError_('VALIDATION','匯入資料有錯誤。',errors);
  var newFieldKeys={};(input.users||[]).forEach(function(raw){var account=String(raw.account).trim(),old=map[account],profile=Object.assign({},old?parseJson_(old.profile_json,{}):{},raw.profile||{});Object.keys(profile).forEach(function(k){if(k)newFieldKeys[k]=true;});if(old&&mode==='skip')return;if(old&&mode==='cancel')throw apiError_('DUPLICATE','發現重複帳號：'+account);map[account]={account:account,password_hash:raw.password?sha256_(String(raw.password).trim()):old.password_hash,profile_json:JSON.stringify(mode==='updateNonBlank'?Object.keys(profile).reduce(function(o,k){if(profile[k]!=='')o[k]=profile[k];return o;},{}):profile),status:raw.status||'active',created_at:old?old.created_at:now_(),updated_at:now_()};});replaceAll_(sheet,Object.keys(map).map(function(k){return map[k];}));
  if(fieldSheet){var existingKeyMap={};existingFields.forEach(function(f){existingKeyMap[f.field_key]=true;});var addedFields=[];Object.keys(newFieldKeys).forEach(function(k){if(!existingKeyMap[k]&&k!=='account'&&k!=='password'){addedFields.push({field_id:Utilities.getUuid(),field_key:k,field_label:k,field_order:existingFields.length+addedFields.length+3,field_type:'text',statistical_dimension:true,active:true});}});if(addedFields.length>0){addedFields.forEach(function(f){append_(fieldSheet,f);});}}
  return {ok:true,data:{count:Object.keys(map).length}};}
function safeUsers_(ss){return rows_(ss.getSheetByName('問卷使用者設定')).map(function(u){return {account:u.account,profile:parseJson_(u.profile_json,{}),status:u.status,createdAt:u.created_at,updatedAt:u.updated_at};});}
function adminUsers_(input){var auth=requireAdminProject_(input);return {ok:true,data:safeUsers_(projectDb_(auth.project))};}
function adminSaveLinkedOptions_(input){var auth=requireAdminProject_(input),ss=projectDb_(auth.project),schema=readSchema_(ss),linkedTypes={linked_multi:true,linked_short:true,linked_matrix:true},questions={},accounts={},seen={};schema.questions.forEach(function(q){if(linkedTypes[q.type])questions[q.id]=true;});rows_(ss.getSheetByName('問卷使用者設定')).forEach(function(u){accounts[String(u.account)]=true;});var records=(input.options||[]).map(function(o,i){var questionId=String(o.questionId===undefined?'':o.questionId).trim(),account=String(o.account===undefined?'':o.account).trim(),value=String(o.value===undefined?'':o.value).trim(),label=String((o.label===undefined||o.label===null)?value:o.label).trim(),record={question_id:questionId,account:account,option_value:value,option_label:label,option_order:Number(o.order||i+1),active:o.active!==false},key=record.question_id+'\u0000'+record.account+'\u0000'+record.option_value;if(!questions[record.question_id])throw apiError_('VALIDATION','連結型選項對應到不存在或不支援的題目。');if(!accounts[record.account])throw apiError_('VALIDATION','找不到使用者：'+record.account);if(!record.option_value||!record.option_label)throw apiError_('VALIDATION','連結型項目不可空白。');if(seen[key])throw apiError_('VALIDATION','同一使用者的連結型項目重複。');seen[key]=true;return record;});replaceAll_(ss.getSheetByName('連結型選項設定'),records);return {ok:true,data:records};}

function adminDisplayName_(adminId){var admin=rows_(master_().getSheetByName('管理員設定')).find(function(a){return a.admin_id===adminId;});return admin&&(admin.admin_name||admin.email)||adminId;}
function responseUpdaterName_(value){var text=String(value||''),match=text.match(/^管理員:(.+)$/);return match?'管理員:'+adminDisplayName_(match[1]):text;}
function adminResponses_(input){var auth=requireAdminProject_(input),ss=projectDb_(auth.project),answers=rows_(ss.getSheetByName('使用者回答')),statuses=rows_(ss.getSheetByName('填寫狀態'));answers.forEach(function(row){row.updated_by=responseUpdaterName_(row.updated_by);});statuses.forEach(function(row){row.updated_by=responseUpdaterName_(row.updated_by);});return {ok:true,data:{answers:answers,statuses:statuses}};}
function adminUpdateResponse_(input){var auth=requireAdminProject_(input),ss=projectDb_(auth.project),account=safeText_(input.account,100);if(!rows_(ss.getSheetByName('問卷使用者設定')).some(function(u){return u.account===account;}))throw apiError_('NOT_FOUND','找不到使用者。');return withLock_(function(){var answers=input.answers||{},status=input.status||'已暫存',schema=readSchema_(ss),visible=visibleQuestionIds_(schema,answers);validateAnswers_(ss,account,schema,answers,visible);if(status==='已送出')applyInventory_(ss,account,schema,answers,'admin_submit');else releaseInventory_(ss,account,schema,'status_reverted');saveAnswers_(ss,account,answers,status,'管理員:'+adminDisplayName_(auth.admin.admin_id),status==='已送出');logProject_(auth.project,'管理員',auth.admin.admin_id,'管理員修改回答','回答',account,'代為修改回答');return {ok:true};});}
function adminInventory_(input){var auth=requireAdminProject_(input),ss=projectDb_(auth.project);return {ok:true,data:inventoryAdminData_(ss)};}
function adminAdjustInventory_(input){var auth=requireAdminProject_(input),ss=projectDb_(auth.project);return withLock_(function(){var remaining=adjustInventory_(ss,safeText_(input.questionId,100),safeText_(input.optionValue,200),input.delta,'管理員:'+auth.admin.admin_id);logProject_(auth.project,'管理員',auth.admin.admin_id,'手動調整庫存','庫存',input.questionId,String(input.optionValue)+' '+input.delta);return {ok:true,data:{remaining:remaining}};});}
function adminStats_(input){var auth=requireAdminProject_(input),ss=projectDb_(auth.project),dimensions=input.dimensions||[],fields=rows_(ss.getSheetByName('使用者欄位設定')),allowed={account:true};fields.forEach(function(f){if(String(f.statistical_dimension)==='true'&&f.field_key!=='password')allowed[f.field_key]=true;});safeUsers_(ss).forEach(function(u){Object.keys(u.profile||{}).forEach(function(k){if(k&&k!=='password')allowed[k]=true;});});dimensions.forEach(function(d){if(!allowed[d])throw apiError_('VALIDATION','不可使用此統計維度。');});return {ok:true,data:{summary:statsFor_(ss),groups:groupStats_(ss,dimensions)}};}
function adminAdvancedAnalytics_(input){var auth=requireAdminProject_(input),ss=projectDb_(auth.project),schema=readSchema_(ss),submitted={};rows_(ss.getSheetByName('填寫狀態')).forEach(function(s){if(s.status==='已送出')submitted[s.account]=true;});var answers=rows_(ss.getSheetByName('使用者回答')).filter(function(a){return submitted[a.account];}),heatmaps=[],maxdiff=[];schema.questions.forEach(function(q){var vals=answers.filter(function(a){return a.question_id===q.id;}).map(function(a){return parseJson_(a.answer_value,[]);});if(q.type==='heatmap'){var points=[];vals.forEach(function(v){(Array.isArray(v)?v:[]).forEach(function(p){if(isFinite(Number(p.x))&&isFinite(Number(p.y)))points.push({x:Math.max(0,Math.min(1,Number(p.x))),y:Math.max(0,Math.min(1,Number(p.y)))});});});heatmaps.push({questionId:q.id,title:q.title,imageUrl:(q.config||{}).imageUrl||'',responses:vals.length,points:points});}if(q.type==='maxdiff'){var score={};(q.options||[]).forEach(function(o){score[o.value]={value:o.value,label:o.label,best:0,worst:0,shown:0};});vals.forEach(function(v){(Array.isArray(v)?v:[v]).forEach(function(r){if(!r)return;(r.set||[]).forEach(function(id){if(score[id])score[id].shown++;});if(score[r.best])score[r.best].best++;if(score[r.worst])score[r.worst].worst++;});});maxdiff.push({questionId:q.id,title:q.title,utilities:Object.keys(score).map(function(id){var s=score[id];s.utility=s.shown?Math.round((s.best-s.worst)/s.shown*10000)/10000:0;return s;}).sort(function(a,b){return b.utility-a.utility;})});}});return {ok:true,data:{heatmaps:heatmaps,maxdiff:maxdiff}};}
function statsFor_(ss){var users=safeUsers_(ss),statuses=rows_(ss.getSheetByName('填寫狀態')),by={};statuses.forEach(function(s){by[s.account]=s;});var submitted=0,draft=0,loggedIn=0;if(users.length>0){users.forEach(function(u){var s=by[u.account];if(s&&s.last_login_at)loggedIn++;if(s&&s.status==='已送出')submitted++;else if(s&&['已暫存','填寫中'].indexOf(s.status)>=0)draft++;});return {total:users.length,loggedIn:loggedIn,neverLoggedIn:users.length-loggedIn,draft:draft,submitted:submitted,notSubmitted:users.length-submitted,rate:Math.round(submitted/users.length*10000)/100};}else{statuses.forEach(function(s){if(s.last_login_at)loggedIn++;if(s.status==='已送出')submitted++;else if(['已暫存','填寫中'].indexOf(s.status)>=0)draft++;});var total=statuses.length;return {total:total,loggedIn:loggedIn,neverLoggedIn:0,draft:draft,submitted:submitted,notSubmitted:total-submitted,rate:total?Math.round(submitted/total*10000)/100:0};}}
function groupStats_(ss,dims){if(!dims.length)return[];var status={};rows_(ss.getSheetByName('填寫狀態')).forEach(function(s){status[s.account]=s.status;});var groups={};safeUsers_(ss).forEach(function(u){var p=Object.assign({account:u.account},u.profile),vals=dims.map(function(d){return String(p[d]||'未分類');}),key=JSON.stringify(vals);if(!groups[key])groups[key]={values:vals,total:0,submitted:0,accounts:[]};groups[key].total++;groups[key].accounts.push(u.account);if(status[u.account]==='已送出')groups[key].submitted++;});return Object.keys(groups).map(function(k){var g=groups[k];g.rate=g.total?Math.round(g.submitted/g.total*10000)/100:0;return g;});}
function filterLogs_(ss,startDate,endDate){
  var start=startDate?new Date(String(startDate)+'T00:00:00').getTime():null,end=endDate?new Date(String(endDate)+'T23:59:59.999').getTime():null;
  if(start!==null&&!isFinite(start))throw apiError_('VALIDATION','開始日期格式錯誤。');
  if(end!==null&&!isFinite(end))throw apiError_('VALIDATION','結束日期格式錯誤。');
  if(start!==null&&end!==null&&start>end)throw apiError_('VALIDATION','開始日期不可晚於結束日期。');
  return rows_(ss.getSheetByName('專案操作紀錄')).filter(function(r){var time=new Date(r.created_at).getTime();return (start===null||time>=start)&&(end===null||time<=end);}).reverse();
}
function adminLogs_(input){
  var auth=requireAdminProject_(input),page=Math.max(1,Math.floor(Number(input.page)||1)),pageSize=Math.min(100,Math.max(1,Math.floor(Number(input.pageSize)||100))),ss=projectDb_(auth.project),sheet=ss.getSheetByName('專案操作紀錄');
  // The normal view is by far the most common path. Read only the requested rows
  // from the bottom of the append-only sheet instead of materialising the entire
  // audit history on every page change.
  if(!input.startDate&&!input.endDate){
    var total=Math.max(0,sheet.getLastRow()-1),totalPages=Math.max(1,Math.ceil(total/pageSize));
    page=Math.min(page,totalPages);
    var newestOffset=(page-1)*pageSize,count=Math.min(pageSize,Math.max(0,total-newestOffset)),items=[];
    if(count){
      var firstDataIndex=total-newestOffset-count+1,headers=sheet.getRange(1,1,1,sheet.getLastColumn()).getValues()[0].map(String);
      items=sheet.getRange(firstDataIndex+1,1,count,headers.length).getValues().reverse().map(function(row){var item={};headers.forEach(function(h,i){item[h]=cleanCell_(row[i]);});return item;});
    }
    return {ok:true,data:{rows:items,page:page,pageSize:pageSize,total:total,totalPages:totalPages}};
  }
  var filtered=filterLogs_(ss,input.startDate,input.endDate),total=filtered.length,totalPages=Math.max(1,Math.ceil(total/pageSize));
  page=Math.min(page,totalPages);
  return {ok:true,data:{rows:filtered.slice((page-1)*pageSize,page*pageSize),page:page,pageSize:pageSize,total:total,totalPages:totalPages}};
}
function adminAttachments_(input){var auth=requireAdminProject_(input);return {ok:true,data:rows_(projectDb_(auth.project).getSheetByName('附件紀錄')).filter(function(a){return String(a.active)!=='false';})};}
function adminDeleteAttachment_(input){var auth=requireAdminProject_(input);deactivateAttachment_(projectDb_(auth.project),input.attachmentId);return {ok:true};}
function adminDownloadAllAttachments_(input){
  var auth=requireAdminProject_(input),records=adminAttachments_(input).data;
  if(!records.length)throw apiError_('NOT_FOUND','目前沒有可下載的附件。');
  var blobs=[],missing=0;
  records.forEach(function(a,index){
    try{
      var blob=DriveApp.getFileById(a.drive_file_id).getBlob(),safeAccount=String(a.account||'未知帳號').replace(/[\\/:*?"<>|]/g,'_'),safeName=String(a.file_name||('attachment_'+(index+1))).replace(/[\\/:*?"<>|]/g,'_');
      blob.setName(safeAccount+'_'+safeName);
      blobs.push(blob);
    }catch(_){missing++;}
  });
  if(!blobs.length)throw apiError_('NOT_FOUND','附件檔案已不存在，無法打包下載。');
  var zip=Utilities.zip(blobs,auth.project.project_id+'_attachments.zip');
  logProject_(auth.project,'管理員',auth.admin.admin_id,'下載資料','附件管理','all_attachments','打包下載 '+blobs.length+' 個附件');
  return {ok:true,data:{fileName:zip.getName(),mimeType:'application/zip',base64:Utilities.base64Encode(zip.getBytes()),fileCount:blobs.length,missingCount:missing}};
}
function adminExport_(input){var auth=requireAdminProject_(input),ss=projectDb_(auth.project),kind=input.kind||'wide',csv='';if(kind==='long')csv=longCsv_(ss);else if(kind.indexOf('wide')===0)csv=wideCsv_(ss,kind);else if(kind==='unsubmitted')csv=unsubmittedCsv_(ss);else if(kind==='users')csv=usersCsv_(ss);else if(kind==='status')csv=statusCsv_(ss);else if(kind==='attachments')csv=attachmentsCsv_(ss);else if(kind==='stats')csv=statsCsv_(ss,input.dimensions||[]);else if(kind==='logs')csv=logsCsv_(ss,input.startDate,input.endDate);else csv=wideCsv_(ss,'wide');logProject_(auth.project,'管理員',auth.admin.admin_id,'下載資料','匯出',kind,'下載 CSV');return {ok:true,data:{fileName:auth.project.project_id+'_'+kind+'.csv',mimeType:'text/csv;charset=utf-8',base64:Utilities.base64Encode('\uFEFF'+csv, Utilities.Charset.UTF_8)}};}
function csvCell_(v){var s=typeof v==='string'?v:JSON.stringify(v===undefined?'':v);return '"'+s.replace(/"/g,'""')+'"';}
function longCsv_(ss){
  var schema=readSchema_(ss),questionMap={};
  schema.questions.forEach(function(q){questionMap[q.id]=q;});
  var typeMap={short:'簡答',paragraph:'詳答',single:'單選',checkbox:'多選',dropdown:'下拉',scale:'量表',radio_grid:'單選方陣',checkbox_grid:'多選方陣',date:'日期',time:'時間',number:'數字',email:'Email',phone:'電話',heading:'標題',image_note:'圖片',section:'區段',signature:'簽名',multi_image:'多圖',linked_multi:'連結型多選',linked_short:'連結型簡答',linked_matrix:'連結型矩陣'};
  var rows=rows_(ss.getSheetByName('使用者回答')),headers=['帳號','問題','題型','回答內容','附件','狀態','建立時間','最後更新','送出時間','更新者'];
  return [headers.map(csvCell_).join(',')].concat(rows.map(function(r){
    var q=questionMap[r.question_id]||{title:r.question_id,type:'未知'};
    return [r.account,q.title,typeMap[q.type]||q.type,r.answer_display||r.answer_value,r.attachment_ids,r.status,r.created_at,r.updated_at,r.submitted_at,r.updated_by].map(csvCell_).join(',');
  })).join('\r\n');
}
function wideCsv_(ss,kind){var schema=readSchema_(ss),users=safeUsers_(ss),answers=rows_(ss.getSheetByName('使用者回答')),map={},statuses={};rows_(ss.getSheetByName('填寫狀態')).forEach(function(s){statuses[s.account]=s.status;});answers.forEach(function(a){(map[a.account]||(map[a.account]={}))[a.question_id]=parseJson_(a.answer_value,a.answer_value);});if(kind==='wide_submitted')users=users.filter(function(u){return statuses[u.account]==='已送出';});if(kind==='wide_draft')users=users.filter(function(u){return statuses[u.account]==='已暫存'||statuses[u.account]==='填寫中';});var headers=['account'].concat(schema.questions.map(function(q){return q.title;}));return [headers.map(csvCell_).join(',')].concat(users.map(function(u){return [u.account].concat(schema.questions.map(function(q){return (map[u.account]||{})[q.id]||'';})).map(csvCell_).join(',');})).join('\r\n');}
function unsubmittedCsv_(ss){var users=safeUsers_(ss),statuses={};rows_(ss.getSheetByName('填寫狀態')).forEach(function(s){statuses[s.account]=s.status;});var unsubmitted=users.filter(function(u){return !statuses[u.account]||statuses[u.account]==='未填寫';});if(!unsubmitted.length)return '';var fieldSheet=ss.getSheetByName('使用者欄位設定'),fields=fieldSheet?rows_(fieldSheet):[];var accountLabel='帳號';var accountField=fields.find(function(f){return f.field_key==='account';});if(accountField&&accountField.field_label)accountLabel=accountField.field_label;var profileKeys=[];unsubmitted.forEach(function(u){Object.keys(u.profile||{}).forEach(function(k){if(k&&profileKeys.indexOf(k)<0)profileKeys.push(k);});});var headers=[accountLabel,'填寫狀態'].concat(profileKeys);return [headers.map(csvCell_).join(',')].concat(unsubmitted.map(function(u){var row=[u.account,'未填寫'];profileKeys.forEach(function(k){row.push((u.profile&&u.profile[k])!==undefined?u.profile[k]:'');});return row.map(csvCell_).join(',');})).join('\r\n');}
function usersCsv_(ss){var users=safeUsers_(ss);if(!users.length)return '';var fieldSheet=ss.getSheetByName('使用者欄位設定'),fields=fieldSheet?rows_(fieldSheet):[];var accountLabel='帳號';var accountField=fields.find(function(f){return f.field_key==='account';});if(accountField&&accountField.field_label)accountLabel=accountField.field_label;var profileKeys=[];users.forEach(function(u){Object.keys(u.profile||{}).forEach(function(k){if(k&&profileKeys.indexOf(k)<0)profileKeys.push(k);});});var headers=[accountLabel].concat(profileKeys);return [headers.map(csvCell_).join(',')].concat(users.map(function(u){var row=[u.account];profileKeys.forEach(function(k){row.push((u.profile&&u.profile[k])!==undefined?u.profile[k]:'');});return row.map(csvCell_).join(',');})).join('\r\n');}
function statusCsv_(ss){var rows=rows_(ss.getSheetByName('填寫狀態'));if(!rows.length)return '';var keys=Object.keys(rows[0]);return [keys.map(csvCell_).join(',')].concat(rows.map(function(r){return keys.map(function(k){return csvCell_(r[k]);}).join(',');})).join('\r\n');}
function attachmentsCsv_(ss){var rows=rows_(ss.getSheetByName('附件紀錄')).filter(function(a){return String(a.active)!=='false';});if(!rows.length)return '';var keys=Object.keys(rows[0]);return [keys.map(csvCell_).join(',')].concat(rows.map(function(r){return keys.map(function(k){return csvCell_(r[k]);}).join(',');})).join('\r\n');}
function statsCsv_(ss,dims){var groups=groupStats_(ss,dims);var headers=dims.concat(['使用者數','已送出','填寫率']);return [headers.map(csvCell_).join(',')].concat(groups.map(function(g){return g.values.concat([g.total,g.submitted,g.rate+'%']).map(csvCell_).join(',');})).join('\r\n');}
function logsCsv_(ss,startDate,endDate){var logs=filterLogs_(ss,startDate,endDate),headers=['log_id','operator_type','operator_id','action','target_type','target_id','description','created_at'];return [headers.map(csvCell_).join(',')].concat(logs.map(function(r){return headers.map(function(k){return csvCell_(r[k]);}).join(',');})).join('\r\n');}

function logMaster_(adminId,projectId,operatorType,operatorId,action,targetType,targetId,description,ss){append_((ss||master_()).getSheetByName('系統操作紀錄'),{log_id:Utilities.getUuid(),admin_id:adminId,project_id:projectId,operator_type:operatorType,operator_id:operatorId,action:action,target_type:targetType,target_id:targetId,description:description,created_at:now_()});}
function logProject_(project,operatorType,operatorId,action,targetType,targetId,description,ss){append_((ss||projectDb_(project)).getSheetByName('專案操作紀錄'),{log_id:Utilities.getUuid(),operator_type:operatorType,operator_id:operatorId,action:action,target_type:targetType,target_id:targetId,description:description,created_at:now_()});}

function adminUpload_(input){var auth=requireAdminProject_(input),account=safeText_(input.account,100);if(!account)throw apiError_('VALIDATION','缺少使用者帳號。');var type=input.type==='signature'?'signature':'image',mime=String(input.mimeType||'').toLowerCase(),allowed={'image/jpeg':'jpg','image/png':'png','image/heic':'heic','image/heif':'heic','image/webp':'webp'};if(type==='signature'&&mime!=='image/png')throw apiError_('VALIDATION','簽名必須為 PNG。');if(!allowed[mime])throw apiError_('VALIDATION','不支援的圖片格式。');var bytes;try{bytes=Utilities.base64Decode(String(input.base64||'').replace(/^data:[^;]+;base64,/,''));}catch(_){throw apiError_('VALIDATION','檔案內容格式錯誤。');}if(!bytes.length||bytes.length>5*1024*1024)throw apiError_('VALIDATION','單一檔案不可超過 5 MB。');assertImageMagic_(bytes,mime);var ss=projectDb_(auth.project),qid=safeText_(input.questionId,100),question=readSchema_(ss).questions.find(function(q){return q.id===qid;});if(!question||(type==='signature'&&question.type!=='signature')||(type==='image'&&question.type!=='multi_image'))throw apiError_('VALIDATION','題型與附件類型不符。');var parent=DriveApp.getFolderById(auth.project.folder_id),iter=parent.getFoldersByName(type==='signature'?'signatures':'uploads'),folder=iter.hasNext()?iter.next():parent.createFolder(type==='signature'?'signatures':'uploads');var name=[auth.project.project_id,account.replace(/[^A-Za-z0-9_-]/g,'_'),qid,Date.now(),input.sequence||1].join('_')+'.'+allowed[mime];var file=folder.createFile(Utilities.newBlob(bytes,mime,name)),id=Utilities.getUuid();append_(ss.getSheetByName('附件紀錄'),{attachment_id:id,account:account,question_id:qid,attachment_type:type,file_name:name,drive_file_id:file.getId(),file_size:bytes.length,mime_type:mime,uploaded_at:now_(),active:true});return {ok:true,data:{attachmentId:id,fileName:name,mimeType:mime,size:bytes.length}};}
function adminQuestionImageUpload_(input){var auth=requireAdminProject_(input),mime=String(input.mimeType||'').toLowerCase(),allowed={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'};if(!allowed[mime])throw apiError_('VALIDATION','題目圖片僅支援 JPG、PNG、WebP。');var bytes;try{bytes=Utilities.base64Decode(String(input.base64||''));}catch(_){throw apiError_('VALIDATION','檔案內容格式錯誤。');}if(!bytes.length||bytes.length>5*1024*1024)throw apiError_('VALIDATION','單一檔案不可超過 5 MB。');assertImageMagic_(bytes,mime);var parent=DriveApp.getFolderById(auth.project.folder_id),iter=parent.getFoldersByName('question-images'),folder=iter.hasNext()?iter.next():parent.createFolder('question-images'),name=['question',safeText_(input.questionId,100),Date.now()].join('_')+'.'+allowed[mime],file=folder.createFile(Utilities.newBlob(bytes,mime,name));file.setSharing(DriveApp.Access.ANYONE_WITH_LINK,DriveApp.Permission.VIEW);return {ok:true,data:{fileId:file.getId(),fileName:name,url:'https://drive.google.com/thumbnail?id='+file.getId()+'&sz=w1600'}};}
