function syncInventoryFromSchema_(ss,schema){var sheet=ss.getSheetByName('庫存設定');if(!sheet)return;var old=rows_(sheet),map={};old.forEach(function(r){map[r.question_id+'|'+r.option_value]=r;});var next=[];(schema.questions||[]).filter(function(q){return q.type==='inventory';}).forEach(function(q){(q.options||[]).forEach(function(o){var key=q.id+'|'+o.value,prev=map[key],initial=Math.max(0,Number(o.stock||0)),remaining=prev?Number(prev.remaining_stock):initial;if(prev&&Number(prev.initial_stock)!==initial)remaining=Math.max(0,remaining+(initial-Number(prev.initial_stock)));next.push({question_id:q.id,option_value:o.value,initial_stock:initial,remaining_stock:remaining,active:true,updated_at:now_()});});});replaceAll_(sheet,next);}
function inventoryMap_(ss){var out={};rows_(ss.getSheetByName('庫存設定')).forEach(function(r){out[r.question_id+'|'+r.option_value]=r;});return out;}
function attachInventory_(ss,schema){var map=inventoryMap_(ss);schema.questions.filter(function(q){return q.type==='inventory';}).forEach(function(q){q.options.forEach(function(o){var r=map[q.id+'|'+o.value];o.remaining=r?Number(r.remaining_stock):0;});});return schema;}
function inventoryQuantities_(schema,answers){var out={};schema.questions.filter(function(q){return q.type==='inventory';}).forEach(function(q){var v=answers[q.id],quantities=v&&typeof v==='object'?v:{};(q.options||[]).forEach(function(o){out[q.id+'|'+o.value]={questionId:q.id,optionValue:o.value,quantity:Math.max(0,Number(quantities[o.value]||0))};});});return out;}
function accountSubmitted_(ss,account){var s=rows_(ss.getSheetByName('填寫狀態')).find(function(r){return r.account===account;});return !!s&&s.status==='已送出';}
function applyInventory_(ss,account,schema,answers,action){var oldAnswers={};if(accountSubmitted_(ss,account))rows_(ss.getSheetByName('使用者回答')).filter(function(r){return r.account===account;}).forEach(function(r){oldAnswers[r.question_id]=parseJson_(r.answer_value,{});});var before=inventoryQuantities_(schema,oldAnswers),after=inventoryQuantities_(schema,answers),sheet=ss.getSheetByName('庫存設定'),stock=inventoryMap_(ss),changes=[];Object.keys(after).forEach(function(key){var delta=after[key].quantity-(before[key]?before[key].quantity:0),r=stock[key];if(!r)throw apiError_('INVENTORY','找不到庫存設定。');if(delta>Number(r.remaining_stock))throw apiError_('INVENTORY_SHORTAGE','選擇的名額已不足。',[{questionId:after[key].questionId,message:'剩餘名額不足，請重新選擇'}]);if(delta!==0)changes.push({row:r,item:after[key],delta:delta});});changes.forEach(function(c){var beforeQty=Number(c.row.remaining_stock),afterQty=beforeQty-c.delta;updateWhere_(sheet,function(r){return r.question_id===c.item.questionId&&r.option_value===c.item.optionValue;},{remaining_stock:afterQty,updated_at:now_()});append_(ss.getSheetByName('庫存異動紀錄'),{transaction_id:Utilities.getUuid(),account:account,question_id:c.item.questionId,option_value:c.item.optionValue,quantity_delta:-c.delta,before_quantity:beforeQty,after_quantity:afterQty,action:action||'submit',created_at:now_()});});}
function releaseInventory_(ss,account,schema,action){if(!accountSubmitted_(ss,account))return;applyInventory_(ss,account,schema,{},action||'release');}
function inventoryAdminData_(ss){return {stock:rows_(ss.getSheetByName('庫存設定')),transactions:rows_(ss.getSheetByName('庫存異動紀錄')).reverse().slice(0,1000)};}
function adjustInventory_(ss,qid,value,delta,operator){delta=Number(delta);if(!isFinite(delta)||Math.floor(delta)!==delta||delta===0)throw apiError_('VALIDATION','調整數量必須是非零整數。');var sheet=ss.getSheetByName('庫存設定'),row=inventoryMap_(ss)[qid+'|'+value];if(!row)throw apiError_('NOT_FOUND','找不到庫存選項。');var before=Number(row.remaining_stock),after=before+delta;if(after<0)throw apiError_('INVENTORY_SHORTAGE','調整後庫存不可小於 0。');updateWhere_(sheet,function(r){return r.question_id===qid&&r.option_value===value;},{remaining_stock:after,updated_at:now_()});append_(ss.getSheetByName('庫存異動紀錄'),{transaction_id:Utilities.getUuid(),account:operator,question_id:qid,option_value:value,quantity_delta:delta,before_quantity:before,after_quantity:after,action:'manual_adjustment',created_at:now_()});return after;}
